### ISSUE TITLE
Config: Ignore local functions

### ISSUE THREAD

**Issue by buhtzz** [PyCQA/mccabe#101]
Hello,

I'm not sue but it seems to me that `mccab` does take local functions into account when calculating the cc score.

Just a stupid example.

```
def foobar():
    def _my_local_function():
        return 'local'

    return _my_local_function()
```

IMHO in some cases there are better reasons to keep a function local then reducing the cc score.

Is there a way to configure mccab that way that it ignore local functions when calculating cc score?

I'm using mccab via flake8 in Emacs via python-lsp-server and eglot package.

**Comment by sigmavirus24** [comment]
There's so little configuration for McCabe that we won't add this. You might try radon instead which integrates with flake8 and had way more knobs than McCabe
