### ISSUE TITLE
Add support for pytest 7+

### ISSUE THREAD

**Issue by slava-shor-emporus** [PyCQA/mccabe#110]
Since pytest version 7.0.0 there were some deprecations to API that emit warnings like:

```
../.venv/lib/python3.11/site-packages/_pytest/nodes.py:146
  /Users/slava/Space/Emporus/emporus-core-runtime/.venv/lib/python3.11/site-packages/_pytest/nodes.py:146: PytestDeprecationWarning: <class 'pytest_mccabe.McCabeItem'> is not using a cooperative constructor and only takes {'fspath', 'parent', 'complexity'}.
  See https://docs.pytest.org/en/stable/deprecations.html#constructors-of-custom-pytest-node-subclasses-should-take-kwargs for more details.
    warnings.warn(

../.venv/lib/python3.11/site-packages/_pytest/nodes.py:686
  /Users/slava/Space/Emporus/emporus-core-runtime/.venv/lib/python3.11/site-packages/_pytest/nodes.py:686: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to McCabeItem is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    super().__init__(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================================================== 7 passed, 14 warnings in 0.03s ===========================================================================================
```

Pytest warns about:
* Necessity to [take kwargs](https://docs.pytest.org/en/stable/deprecations.html#constructors-of-custom-pytest-node-subclasses-should-take-kwargs) and [node type refactoring](https://docs.pytest.org/en/latest/example/nonpython.html)
* Necessity to [switch](https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path) from `fspath` to `pathlib.Path`
* Example of a possible upgrade for [reference](https://github.com/asmeurer/pytest-flakes/pull/40/)

The latest working pytest version is 7.1.4 after which pytest integration fails with an internal error on any version higher.

**Comment by The-Compiler** [comment]
This repository has nothing to do with pytest - and you probably shouldn't be using pytest-mccabe either, see the note at https://pypi.org/project/pytest-mccabe/.

**Comment by slava-shor-emporus** [comment]
Sorry, my bad.
