### ISSUE TITLE
def inside def

### ISSUE THREAD

**Issue by ghost** [PyCQA/mccabe#18]
Hi!

Why def inside def increase complexity of outer function?
def inside def looks like method inside class. Maybe, complexity of inner function should be independent from outer function?

For example, complexity of [test_nested_functions_snippet](https://github.com/flintwork/mccabe/blob/master/test_mccabe.py#L113) equals to 1 instead of 3.

**Comment by adiroiban** [comment]
You might want to have a policy in which all class methods (private or public require an API doc) but
some frameworks (ex Twisted) want you to create multiple functions and chain them.

It would be nice, to provide at least the option to consider embedded method just like normal class method.

**Comment by sigmavirus24** [comment]
> It would be nice, to provide at least the option to consider embedded method just like normal class method.

It would be convenient for users, certainly. If you inspect the project though, there's no place to easily make that distinction without doing some back flips to pre-analyze the AST, and mark things with nested functions as classes instead (i.e., literally changing the AST and invalidating it).

**Comment by adiroiban** [comment]
I did check the current mccabe.py before posting the comment and I agree the implementing this is not  easy.

>  I think the existing behaviour is correct. Changing it to allow for users with bad habits is not what I'm interested in. Classes may look ugly but that doesn't increase their difficulty to understand the code.

From the past conversation, my understanding was that even if I would submit such a patch, it would be rejects, as it is not aligned with the goal of this project.

For me, this was just a weekend hack so I don't really mind if it is not implemented.

I just wanted to check if you still think that this is a bug or a feature :)

**Comment by sigmavirus24** [comment]
So I think turning it off by default is a problem. If there was a way to efficiently pre-process the AST for this (or even to do it just in time) based on a flag (which users would understand could cause significant performance degradation) and provided it's well tested and correct, I wouldn't hesitate to accept a PR because, as you point out, within certain frameworks this is absolutely a necessity of life.

**Comment by sigmavirus24** [comment]
My comment around "users with bad habits" is also more informed by certain projects that I have worked on in the last year and a half that thoroughly abuse closures in this way without needing closures in the first place. So, that was mostly motivated out of frustration with those projects.

**Comment by adiroiban** [comment]
as a follow up note.

maybe this can be integrated into pylint as a custom checker.
I think that pylint already has support for detecting nested def and it has a few checks related to code complexity based on number of arguments.

**Comment by sigmavirus24** [comment]
@adiroiban yeah, pylint might be a better place to integrate this feature
