### ISSUE TITLE
Not working with python 3.5 "async def ..."

### ISSUE THREAD

**Issue by samuelcolvin** [PyCQA/mccabe#36]
It looks like mccabe is ignoring python 3.5 coroutines defined like

```python
async def foobar(a, b, c):
    whatever(a, b, c)
```

I tried it via flake8 version:

    2.5.1 (pep8: 1.7.0, pyflakes: 1.0.0, mccabe: 0.3.1) CPython 3.5.0+ on Linux

**Comment by sigmavirus24** [comment]
I released 0.4.0 today with the fix for this. Thanks for your patience.
