### ISSUE TITLE
Module or package specific complexity limits

### ISSUE THREAD

**Issue by Korijn** [PyCQA/mccabe#40]
Is it possible to set a different complexity limit for a specific package or module? We have an application that has a particularly complicated subpackage (rendering engine related) which really needs a much higher limit, than the remainder of the code.

If not, please point me in the right direction so I can submit a PR that adds the functionality!

**Comment by sigmavirus24** [comment]
So each run of McCabe uses a single complexity value. That's not likely to change because it satisfies something like 98% of our users. Your best bet is to run mccabe on everything *but* that submodule with your one complexity value and then again on that submodule with your other complexity value.
