### ISSUE TITLE
The mccabe complexity output in module flake8

### ISSUE THREAD

**Issue by FuqiangZhangCU** [PyCQA/mccabe#56]
I have found that if a function name appears more than one time in a file, the output of McCabe complexity for this function name only appear once. I think it should output all of them.

**Comment by sigmavirus24** [comment]
A function name will only have one registered associated function, so there's really only complexity for it (and that's the last defined usage of that name). I'm not convinced this needs to change.

**Comment by FuqiangZhangCU** [comment]
So sorry for late. I can't agree more for your reply. Thanks
