### ISSUE TITLE
Python 3.7.0b4 test failures

### ISSUE THREAD

**Issue by hroncok** [PyCQA/mccabe#61]
```
$ tox -e py37
...
============================= test session starts ==============================
platform linux -- Python 3.7.0b4, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: .../mccabe, inifile:
collected 14 items                                                             

test_mccabe.py ..F...........                                            [100%]

=================================== FAILURES ===================================
____________________ McCabeTestCase.test_expr_as_statement _____________________

self = <test_mccabe.McCabeTestCase testMethod=test_expr_as_statement>

    def test_expr_as_statement(self):
        complexity = get_complexity_number(expr_as_statement, self.strio)
>       self.assertEqual(complexity, 1)
E       AssertionError: 2 != 1

test_mccabe.py:192: AssertionError
===================== 1 failed, 13 passed in 0.06 seconds ======================
ERROR: InvocationError: '.../mccabe/.tox/py37/bin/python setup.py test -q'
___________________________________ summary ____________________________________
ERROR:   py37: commands failed
```

 * pytest 3.6.0
 * six 1.11.0
 * py 1.5.3
 * pluggy 0.6.0
 * more_itertools 4.2.0
 * attrs 18.1.0
 * atomicwrites 1.1.5

**Comment by ncoghlan** [comment]
Checking the test, I think this test failure is likely to go away in 3.7.0b5 - there was a planned change to the way docstrings were handled which we ended up reverting after we realised that it was affecting more than just functions and classes.

That said, switching to a non-docstring expression-as-statement in the example would make this test resilient against any future changes in this area (e.g. making it a numeric literal, like `0x_CAFE_F00D`).

**Comment by sigmavirus24** [comment]
@hroncok @ncoghlan I'd accept a PR that changes the test to using a literal like that for future-proofing purposes. (Although I'm certain whoever wrote this test thought that docstrings were future-proof too :smile: )

**Comment by hroncok** [comment]
On it.

**Comment by hroncok** [comment]
I've just spend a minute trying to figure out why 0x_CAFE_F00D doesn't work on Python 3.5 :roll_eyes:
