### ISSUE TITLE
'noqa: C901' does not work as documented

### ISSUE THREAD

**Issue by raxod502** [PyCQA/mccabe#70]
I have the following code:

```python
# noqa: C901
def complex_function():
    if True:
        if True:
            pass
        else:
            pass
    else:
        if True:
            pass
        else:
            pass
```

I disabled `mccabe` for the function, so I should not be seeing any error. Instead, I get this:

```
$ flake8 --max-complexity 3 cyclo.py
cyclo.py:2:1: C901 'complex_function' is too complex (4)
```

How do I disable `mccabe` for a single function?

```
$ flake8 --version
3.7.6 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.0) CPython 3.7.2 on Darwin
```

**Comment by sigmavirus24** [comment]
A few things:

1. McCabe doesn't implement `# noqa` - Flake8 does
2. `# noqa` in Flake8 belongs on the line that's being reported. So in your example, the line number is 2 which corresponds with `def complex_function():` so instead this should look like


```py
def complex_function():  # noqa: C901
    ...
```

3. Issue trackers are not for Q&A, they're for bug reports. Use [stackoverflow](https://stackoverflow.com) for questions.

**Comment by raxod502** [comment]
Note for future visitors --

Moving the `noqa` line does fix the problem for:

```
$ flake8 --max-complexity 3 cyclo.py
cyclo.py:2:1: C901 'complex_function' is too complex (4)
```

However, it does **not** fix the problem for:

```
$ python3 -m mccabe --min 3 cyclo.py
1:0: 'complex_function' 4
```

This is because (as far as I can tell) `mccabe` does not provide any way to silence warnings, and you must use `flake8` with `mccabe` as a plugin if you want that functionality.

**Comment by sigmavirus24** [comment]
That's correct @raxod502
