### ISSUE TITLE
ignore guard clauses

### ISSUE THREAD

**Issue by wbolster** [PyCQA/mccabe#72]
hi all,

_guard clauses_ are a neat way to reduce complexity (and indenting) of code, since the ‘main flow’ is the ‘happy path’, while the ‘unhappy paths’ lead to raising exceptions, returning early, or `break`/`continue` from a loop.

for example:

```python
def f():
    if error_condition:
        raise ...
    
    a()
    if error_condition:
        raise ...

    b()
    if error_condition:
        raise ...
```

something similar for early returns:

```python
def f():
    if check_something():
        return

    a()

    if error:
       return

    result = ...
    return result
```

and a loop example:

```python
for item in ...:
    if ...:
        break  # or continue
    if ...:
        break  # or continue

    actual_work_goes_here()
```

right now, code like below is an easy way to make the complexity go up (and potentially break `flake8` linting, for example):

```python
def f():
    if False:
        return
    if False:
        return
    if False:
        return
    if False:
        return
    if False:
        return
    if False:
        return
    if False:
        return
    if False:
        return
```

would it be useful to make it possible to _not_ count such constructs for complexity metrics?

the generic pattern would be something along those lines:

* `if` ast node has a single child node
* this should be a `return` / `continue` / `break` statement

i'm not sure this is even possible or desirable, so i'm just dumping this idea here since others may have useful thoughts to add.

**Comment by sigmavirus24** [comment]
> would it be useful to make it possible to not count such constructs for complexity metrics?

There are other measures for complexity measurement but the McCabe measure counts all branches. One of these if statements makes 2 branches in the code. Any time we don't exit early, we see another set of 2 branches (guarded branch, happy branch). As far as the measure that this library implements, we're calculating the complexity metric appropriately.

I think `radon` has other measures that may be of interest to you as well as a flake8 plugin.

**Comment by wbolster** [comment]
thanks, [radon](https://radon.readthedocs.io/) looks interesting.
