### ISSUE TITLE
state project maintenance status

### ISSUE THREAD

**Issue by ssbarnea** [PyCQA/mccabe#79]
As I see that last commit was made more than 6 months ago, that there are open PRs more than two years old and that last release is was about 3 years ago, it makes me feel that the project is not maintained.

Is that true or is only deeply dormant?

The fact that it is not possible to increase complexity limit using `# noqa` seems like something that drives people towards dropping it. Currently there is nothing that can prevent a noqa function from increasing its complexity so, while trying to keep complexity limited you are sometimes forced to add exceptions, once added nothing will prevent them from growing, creating a vicious cycle.

**Comment by sigmavirus24** [comment]
It's a project with very few needs. The older PRs you point out were never going to be accepted but I never did get around to explaining that.

> The fact that it is not possible to increase complexity limit using `# noqa` seems like something that drives people towards dropping it.

Can you point to any evidence of this? I'm not familiar with this complaint. How are you using `mccabe` such that it doesn't work with `# noqa`? How is this supposed to work in your ideal world? I'm struggling to understand what you're even asking for here.

> Currently there is nothing that can prevent a noqa function from increasing its complexity so, while trying to keep complexity limited you are sometimes forced to add exceptions, once added nothing will prevent them from growing, creating a vicious cycle.

Again, I'm not following here

**Comment by ssbarnea** [comment]
Thanks for the quick reply, I tried to describe my issue on https://github.com/PyCQA/mccabe/issues/80

I am happy the see that the project is maintained. Maybe the only thing needed is to close those outdated PRs.
