### ISSUE TITLE
optparse 'type' option no longer accepts strings

### ISSUE THREAD

**Issue by kleptog** [PyCQA/mccabe#82]
This is generating the following warning in flake8:
```
WARNING  flake8.options.manager:manager.py:207 option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
```
The error is here:
https://github.com/PyCQA/mccabe/blob/4b287e2c282606fa870d855837979a39e0b2cb0d/mccabe.py#L245
and here:
https://github.com/PyCQA/mccabe/blob/4b287e2c282606fa870d855837979a39e0b2cb0d/mccabe.py#L322

**Comment by whyscream** [comment]
Could we please see a new release of the `mccabe` plugin on pypi including this fix?
