### ISSUE TITLE
Release mccabe > 0.6.1 to remove pytest-runner requirement?

### ISSUE THREAD

**Issue by cjwatson** [PyCQA/mccabe#90]
Current `flake8` requires `mccabe >= 0.6.0, < 0.7.0`, which means that if you use `flake8` then there's currently no way to avoid the deprecated requirement of `pytest-runner` that was removed over a year ago in 9274755156.  This seems unfortunate.  Is there anything blocking a release, and/or can anyone do anything to help?

**Comment by asottile** [comment]
via 835a5400881b7460998be51d871fd36f836db3c9
